### ISSUE TITLE
Min NodeJS version?

### ISSUE THREAD

**Issue by jahirfiquitiva** [wesbos/twitter-unfollower#3]
Hi Wes

I was trying to run the script and noticed some "issues":

* `TypeError: usersChunked.flat is not a function`
Which I "solved" by doing what was suggested in this [StackOverflow answer](https://stackoverflow.com/a/50993569/4864104)

* `TypeError: Promise.allSettled is not a function`
Which I "solved" by changing it to `Promise.all`

(Probably not the best options, but they worked 😬)

I was wondering if there's a min required NodeJS version or something to properly run the script, so maybe you could mention it on the README.

Or maybe even make the script a little backwards compatible? 😅 

Thanks for your work anyways. 👏 🤗

**Comment by wesbos** [comment]
hey! yah you need node version 11 or greater to get array.flat(). ill add it to the docs
